import React from 'react'
import { Navbar } from '../Components/Navbar'
import { Footer } from '../Components/Footer'


export const PrivacyPolicy = () => {
    return (
        <>
            <Navbar />

            <section className='px-12 mb-16 mt-8'>
                <div className='text-center'>
                    <h3 className='urua-text text-3xl font-semibold py-4 px-8'>Privacy Policy</h3>
                    <p>Urua Privacy policy 1. About this policy This Privacy policy provides information on how Urua collects and processes your data when you visit our website or mobile applications. It sets out what we do with your data and how we keep it secure and explains the rights that you have about your data.
                        2. Who We AreUrua is the leading digital market platform where people(vendors & consumers)can buy and sell goods and services at the comfort of their houses.
                        3. The Data We Collect About You?Personal data means any information that can be used to identify directly or indirectly a specific individual. We collect your data to provide tailored products and services and to analyse and continually improve our products and services. We may collect, use, store and transfer different kinds of personal data for marketing and personal data optimization purposes.
                        You provide us with your data when you register your details on our website and mobile platforms and transact with the same. The personal data we collect includes:1. Information you provide to us: We receive and store the information you provide to us including your identity data, contact data, biometric data, delivery address and financial data. These types of personal data may include:2. contact details (such as your name, postal addresses, phone numbers and email addresses),3. demographic information (such as your date of birth, age or age range and gender),4. online registration information (such as your password and other authentication information),5. payment information (such as your credit card information and billing address),6. information provided as part of online questionnaires (such as responses to any customer satisfaction surveys or market research),7. competition entries/submissions, and8. In certain cases your marketing preferences.
                        2. Information we automatically collect/generate or obtain from third parties: We automatically collect and store certain types of information regarding your use of the Urua marketplace including information about your searches, views, downloads and purchases. In addition, we may receive information about you from third parties including our carriers; payment service providers; merchants/brands; and advertising service providers.
                        These types of personal data may relate to your device (such as your PC, tablet or other mobile devices), your use of our websites and apps (as well as certain third-party websites with whom we have partnered), and/or your personal preferences, interests, or geographic location. Examples of these types of information include:    1. name and age (or predicted age range),    2. information about your device, operating system, browser and IP address,    3. unique identifiers associated with your device,    4. details of web pages that you have visited,    5. which products you have looked at online (including information about products you have searched for or viewed, purchased or added to an online shopping basket),
                        We strive to provide you with choices regarding the Personal Data that you provide to us. Where required by law, if you wish to have your Data used by Urua to provide you with a personalized experience/targeted advertising & content, you can indicate so through the relevant tick-box(es) located on the registration form or by answering the question(s) presented by Urua representatives. If you decide that you no longer wish to benefit from this personalization, you can opt-out or adjust your preferences at any time by closing your account or by sending an email to our official account. You can close your account by clicking on the link that will be displayed on the screen and following the instructions. Once your account is closed, all products and services that you access through your account will no longer be available.
                        4. Cookies and Other Identifiers A cookie is a small file of letters and numbers that we put on your computer, mobile phone or tablet if you agree. Cookies allow us to distinguish you from other users of our website and mobile applications, which helps us to provide you with an enhanced browsing experience. For more information about cookies and how we use them, please read our Cookie Notice:
                        5. How We Use Your DataWe use your data to operate, provide, develop and improve the products and services that we offer, including the following:1. Registering you as a new customer.2. Processing and delivering your orders.3. Managing your relationship with us.4. Enabling you to participate in promotions, competitions and surveys.5. Improving our website, applications, products and services.6. Recommending/advertising products or services that may be of interest to you.7. Enabling you to access certain products and services offered by our partners and vendors. 8. Complying with our legal obligations, including verifying your identity where necessary.9. Detecting fraud.
                        6. Legal basis for the processing of Personal Data We will only process your data where we have a legal basis to do so. The legal basis will depend on the purposes for which we have collected and used your data. In almost every case the legal basis will be one of the following:1. Consent: For example, where you have provided your consent to receive certain marketing from us. You can withdraw your consent at any time, including by clicking on the “unsubscribe” link at the bottom of any marketing email we send you2. Our legitimate business interests: Where we must understand our customers, promote our services and operate effectively, provided in each case that this is done in a legitimate way that does not unduly affect your privacy and other rights. 3. Performance of a contract with you: This would also apply where we need to take steps before entering into a contract with you. For example, you have purchased a product from us and we need to use your contact details and payment information to process your order and send the product to you.4. Compliance with law: We are subject to a legal obligation and need to use your data to comply with that obligation.
                        7. How We Share Your DataA. We may need to share your data with third parties for the following purposes:1. Sale of products and services: To deliver products and services purchased on our marketplace from third parties, we may be required to provide your data to such third parties.2. Working with third-party service providers: We engage third parties to perform certain functions on our behalf. Examples include fulfilling orders for products or services, delivering packages, analyzing data, providing marketing assistance, processing payments, transmitting content, assessing and managing credit risk, and providing customer service.3. Business transfers: As we continue to develop our business, we might sell or buy other businesses or services. In such transactions, customer information may be transferred together with other business assets.4. Detecting fraud and abuse: We release account and other personal data to other companies and organizations for fraud protection and credit risk reduction, and to comply with applicable law.B. When we share your data with third parties we:1. require them to agree to use your data following the terms of this Privacy Notice, our Privacy Policy and in accordance with applicable law; and2. Only permit them to process your data for specified purposes and follow our instructions. We do not allow our third-party service providers to use your data for their purposes.8. International TransfersWe may transfer your data to locations in another country if this is permissible under applicable laws in your location. There are inherent risks in such transfers.  In the event of international transfers of your data, we shall put in place the measures necessary to protect your data and ensure the same level of protection available in the country of data origin. We shall continue to respect your legal rights under the terms of this Privacy Notice and applicable laws in your location.
                        9. Data Retention We will take every reasonable step to ensure that your data is processed for the minimum period necessary for the purposes set out in this Privacy Notice. Your Data may be retained in a form that allows for identification only for as long as: A. We maintain an ongoing relationship with you. This will enable us to improve your experience with us and ensure that you receive communications from usB. Your Data is necessary in connection with the purposes set out in this Privacy Notice and we have a valid legal basis,C. The duration of: (i) any applicable limitation period (i.e., any period during which a person could bring a legal claim against us), andWe will actively review the personal data we hold and delete it securely, or in some cases anonymise it, when there is no longer a legal, business or consumer need for it to be retained.
                        10. Data SecurityWe have put in place security measures to prevent your data from being accidentally lost, used or accessed in an unauthorised way, altered or disclosed.  In addition, we limit access to your data to those employees, agents, contractors and other third parties who have a business need to know. They will only process your data on our instructions and they are subject to a duty of confidentiality.  We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator of a breach where we are legally required to do so.

                        11. Your Legal RightsA. It is important that the personal data we hold about you is accurate and current. Please keep us informed if your data changes during your relationship with us.B. Under certain circumstances, you have rights under data protection laws with your data, including the right to access, correct or erase your data, object to or restrict processing of your data, right to ask that we transfer your data to a third party, and unsubscribe from our emails and newsletters. C. Where you wish to permanently delete your data from our website and other applications, you can choose the option of closing your account. You can close your account by clicking on this link and following the instructions. Once your account is closed, all products and services that you access through your account will no longer be available.D. We can refuse to accede to your request where it is unreasonable or where you have failed to provide additional information necessary to confirm your identity.
                        12. Data Controllers & Contact If you have any questions or concerns about Urua’s Privacy Notice or you are looking for more information on how we process your data, or wish to exercise your legal rights in respect of your data, please contact the Data Privacy Officer through our official email account.We will investigate any complaint about the way we manage Personal Data and ensure that we respond to all substantiated complaints within prescribed timelines.  13. Related Practices and Information A. Cookie Notice B. Terms and Conditions</p>
                </div>
            </section>

            <Footer />
        </>
    )
}
